# Generated by Django 2.0 on 2020-06-19 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'max_length': '最大只能填写12个字符', 'unique': '用户名只能唯一'}, max_length=12, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
    ]
