# Generated by Django 2.0 on 2020-07-01 05:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('boy', '男'), ('girl', '女')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
    ]
