# Generated by Django 2.0 on 2020-08-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200806_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=models.TextField(verbose_name='商品详情'),
        ),
    ]
