# Generated by Django 2.0 on 2020-08-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200806_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='goodsdetail', verbose_name='图片路径'),
        ),
    ]
