# Generated by Django 2.0 on 2020-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='users',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
